source: https://github.com/frolink/Matho

features:
  - node lts
  - ssl

nginx:
  passenger:
    enabled: "on"
    app_start_command: env PORT=$PORT node apps/api/dist/main.js

commands:
  - npm install
  - npm run db:generate
  - npx turbo run build --filter=@matho/api