name: MATHO CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install Dependencies
        run: npm install

      - name: Generate Prisma Client
        run: npm run db:generate

      - name: Build Web
        run: npx turbo run build --filter=@matho/web

      - name: Build API
        run: npx turbo run build --filter=@matho/api
